# Generated by Django 4.2.2 on 2023-07-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todo_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
