# Generated by Django 4.2.2 on 2023-07-24 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_todo_options_rename_name_todo_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(default='', max_length=254)),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('comment_text', models.TextField(max_length=2000, verbose_name='Текст комментария')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.todo', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
