# Generated by Django 4.2.2 on 2023-07-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='pos',
            new_name='post',
        ),
    ]
